apiVersion : apps/v1
kind : Deployment
metadata :
  name : cicd-demo
spec :
  replicas : 2
  selector :
    matchLabels :
      app : cicd-demo
  template :
    metadata :
      labels :
        app : cicd-demo
    spec :
      containers :
      - name : cicd-demo
        image : avishkarnagtile25/cicd-demo:latest
        ports :
        - containerPort : 3000     