name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # -----------------------------
      # Docker Login
      # -----------------------------
      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # -----------------------------
      # Build Docker Image
      # -----------------------------
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-demo:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/cicd-demo:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/cicd-demo:latest

      # -----------------------------
      # Push Docker Image
      # -----------------------------
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd-demo:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd-demo:latest

      # -----------------------------
      # Setup Kubernetes Access
      # -----------------------------
      - name: Setup Kubernetes Access
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl config use-context minikube
          kubectl get nodes

      # -----------------------------
      # Deploy to Minikube
      # -----------------------------
      - name: Restart Deployment
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl rollout restart deployment cicd-demo
          kubectl rollout status deployment cicd-demo
