name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - ci-cd-demo-branch

jobs:
  build-push-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}" --password-stdin

      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-demo:latest .

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd-demo:latest

      - name: Restart Deployment
        run: kubectl rollout restart deployment cicd-demo