name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - ci-cd-demo-branch

jobs:
  build-push-deploy:
    runs-on: self-hosted

    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/cicd-demo
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker Image
        run: docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/cicd-demo cicd-demo=$IMAGE_NAME:$IMAGE_TAG
          kubectl rollout status deployment/cicd-demo
